#ifndef _LEGACY_RESULT_DIGEST_TYPE_COMPAT_H_
#define _LEGACY_RESULT_DIGEST_TYPE_COMPAT_H_

enum ResultDigestType
{
	RESULT_DIGEST_UNKNOWN = -1,
	RESULT_DIGEST_MD5 = 0,
	RESULT_DIGEST_SHA1,
	RESULT_DIGEST_SHA256,
	RESULT_DIGEST_SHA512
};

#endif
