<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemDefinitionGroup>
    <ClCompile>
      <BufferSecurityCheck>true</BufferSecurityCheck>
      <SDLCheck>true</SDLCheck>
      <ControlFlowGuard>Guard</ControlFlowGuard>
    </ClCompile>
    <Link>
      <RandomizedBaseAddress>true</RandomizedBaseAddress>
      <DataExecutionPrevention>true</DataExecutionPrevention>
      <ControlFlowGuard>Guard</ControlFlowGuard>
    </Link>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Platform)'=='x64'">
    <Link>
      <HighEntropyVA>true</HighEntropyVA>
    </Link>
  </ItemDefinitionGroup>
</Project>
