<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalOptions>/utf-8 %(AdditionalOptions)</AdditionalOptions>
    </ClCompile>
    <ResourceCompile>
      <AdditionalOptions>/c65001 %(AdditionalOptions)</AdditionalOptions>
    </ResourceCompile>
  </ItemDefinitionGroup>
  <Import Project="$(MSBuildThisFileDirectory)NativeOpenSslVendor.targets" Condition="Exists('$(MSBuildThisFileDirectory)NativeOpenSslVendor.targets')" />
</Project>
