namespace FHash.UnitTests;

public sealed class HashContractUnitTests
{
    [Fact]
    public void HashRequest_DefinesStableFileAlgorithmAndUppercaseContract()
    {
        string request = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashRequest.h");
        string requestProjection = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashRequestProjection.h");

        Assert.Contains("struct HashRequest", request, StringComparison.Ordinal);
        Assert.Contains("TStrVector files;", request, StringComparison.Ordinal);
        Assert.Contains("std::vector<ResultDigestType> algorithms;", request, StringComparison.Ordinal);
        Assert.Contains("bool uppercaseDigest;", request, StringComparison.Ordinal);
        Assert.Contains("VisitHashRequestFiles(const HashRequest& request", request, StringComparison.Ordinal);
        Assert.Contains("VisitHashRequestAlgorithms(const HashRequest& request", request, StringComparison.Ordinal);
        Assert.Contains("HasHashRequestAlgorithm(const HashRequest& request, ResultDigestType digestType)", request, StringComparison.Ordinal);
        Assert.DoesNotContain("CreateHashRequest(const ThreadData& threadData)", request, StringComparison.Ordinal);
        Assert.Contains("CreateHashRequest(const ThreadData& threadData)", requestProjection, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/ThreadDataExecutionAccess.h\"", requestProjection, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/ThreadDataInputAccess.h\"", requestProjection, StringComparison.Ordinal);
    }

    [Fact]
    public void HashResult_ProjectsStableCoreAndDigestContract()
    {
        string global = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\Global.h");
        string result = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashResult.h");
        string projection = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashResultProjection.h");
        string resultNetProjection = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\ResultNetProjection.h");
        string search = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashResultSearch.h");
        string metadata = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\ResultDigestMetadataAccess.h");

        Assert.Contains("enum ResultDigestType", global, StringComparison.Ordinal);
        Assert.Contains("struct HashDigestResult", global, StringComparison.Ordinal);
        Assert.Contains("struct HashFileMeta", global, StringComparison.Ordinal);
        Assert.Contains("struct HashResult", global, StringComparison.Ordinal);
        Assert.Contains("std::vector<sunjwbase::tstring> values;", global, StringComparison.Ordinal);
        Assert.Contains("std::vector<bool> enabled;", global, StringComparison.Ordinal);
        Assert.DoesNotContain("struct ResultDigestCompatibilityFields", global, StringComparison.Ordinal);
        Assert.DoesNotContain("const ResultData *sourceResult;", result, StringComparison.Ordinal);
        Assert.Contains("std::vector<HashDigestResult> digests;", global, StringComparison.Ordinal);
        Assert.Contains("const HashResult& ProjectHashResult(const HashResult& result)", result, StringComparison.Ordinal);
        Assert.Contains("ProjectHashResult(const ResultData& result)", result, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/ResultNetProjection.h\"", projection, StringComparison.Ordinal);
        Assert.DoesNotContain("#include \"Common/ResultDataProjection.h\"", projection, StringComparison.Ordinal);
        Assert.Contains("AssignHashResultCoreToNet", projection, StringComparison.Ordinal);
        Assert.Contains("AssignHashResultDigestsToNet", projection, StringComparison.Ordinal);
        Assert.Contains("ProjectHashResultToNet(const HashResult& result, TStringConverter convertString)", projection, StringComparison.Ordinal);
        Assert.Contains("AssignResultDigestToNet(TResultDataNet resultDataNet, ResultDigestType digestType, TResultString digestValue)", resultNetProjection, StringComparison.Ordinal);
        Assert.Contains("ConvertResultStateToNet(ResultState resultState)", resultNetProjection, StringComparison.Ordinal);
        Assert.Contains("NormalizeHashResultPathSearchText(const sunjwbase::tstring& pathText)", search, StringComparison.Ordinal);
        Assert.Contains("NormalizeHashResultDigestSearchText(const sunjwbase::tstring& digestText)", search, StringComparison.Ordinal);
        Assert.Contains("VisitProjectedHashResults(const HashResultList& resultList, TStringConverter convertString, TResultVisitor visitor)", projection, StringComparison.Ordinal);
        Assert.Contains("VisitHashResults(resultList, [&](const HashResult& hashResult)", projection, StringComparison.Ordinal);
        Assert.Contains("VisitMatchingHashResults(resultList, predicate, [&](const HashResult& hashResult)", projection, StringComparison.Ordinal);
        Assert.Contains("CountMatchingHashResults(resultList, predicate)", projection, StringComparison.Ordinal);
        Assert.Contains("CreateProjectedDigestMatchingHashResults(const HashResultList& resultList, const sunjwbase::tstring& digestText", projection, StringComparison.Ordinal);
        Assert.Contains("HashResultContainsDigest(const HashResult& result, const sunjwbase::tstring& digestText)", search, StringComparison.Ordinal);
        Assert.Contains("HashResultMatchesDigestText(const HashResult& result, const sunjwbase::tstring& digestText)", search, StringComparison.Ordinal);
        Assert.Contains("HashResultMatchesPathText(const HashResult& result, const sunjwbase::tstring& pathText)", search, StringComparison.Ordinal);
        Assert.Contains("HashResultMatchesPathAndDigestText(const HashResult& result, const sunjwbase::tstring& pathText, const sunjwbase::tstring& digestText)", search, StringComparison.Ordinal);
        Assert.Contains("VisitPathAndDigestMatchingHashResults(const HashResultList& resultList, const sunjwbase::tstring& pathText, const sunjwbase::tstring& digestText, THashResultVisitor visitor)", search, StringComparison.Ordinal);
        Assert.Contains("VisitResultDigestMetadataValues(result", result, StringComparison.Ordinal);
        Assert.Contains("GetResultDigestMetadataStableName(const ResultDigestMetadata& digestMetadata)", metadata, StringComparison.Ordinal);
    }

    [Fact]
    public void ProgressEvent_DefinesSemanticLifecycleSurface_AndObserverCompatibilityDispatch()
    {
        string progressEvent = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\ProgressEvent.h");
        string progressSink = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashProgressSink.h");
        string observer = RepositoryTestContext.ReadTextFile(@"trunk\source\Adapters\UiBridge\HashEngineObserver.h");
        string legacyObserverPath = Path.Combine(RepositoryTestContext.RepoRoot, @"trunk\source\Common\HashEngineObserver.h");
        string legacyBridgePath = Path.Combine(RepositoryTestContext.RepoRoot, @"trunk\source\Common\HashEngineBridge.h");
        string legacyUiBridgeBasePath = Path.Combine(RepositoryTestContext.RepoRoot, @"trunk\source\Common\UIBridgeBase.h");

        Assert.Contains("enum ProgressEventType", progressEvent, StringComparison.Ordinal);
        Assert.Contains("PROGRESS_EVENT_JOB_PREPARING", progressEvent, StringComparison.Ordinal);
        Assert.Contains("PROGRESS_EVENT_FILE_HASH_READY", progressEvent, StringComparison.Ordinal);
        Assert.DoesNotContain("CreateResultProgressEvent(ProgressEventType eventType, const ResultData& result)", progressEvent, StringComparison.Ordinal);
        Assert.DoesNotContain("CreateFileStartedProgressEvent(const ResultData& result)", progressEvent, StringComparison.Ordinal);
        Assert.DoesNotContain("CreateFileMetaReadyProgressEvent(const ResultData& result)", progressEvent, StringComparison.Ordinal);
        Assert.DoesNotContain("CreateFileHashReadyProgressEvent(const ResultData& result, bool uppercaseDigest)", progressEvent, StringComparison.Ordinal);
        Assert.DoesNotContain("CreateFileFailedProgressEvent(const ResultData& result)", progressEvent, StringComparison.Ordinal);
        Assert.Contains("CreateFileHashReadyProgressEvent(const HashResult& result, bool uppercaseDigest)", progressEvent, StringComparison.Ordinal);
        Assert.Contains("CreateResultProgressEvent(ProgressEventType eventType, const HashResult& result)", progressEvent, StringComparison.Ordinal);

        Assert.Contains("class HashProgressSink", progressSink, StringComparison.Ordinal);
        Assert.Contains("virtual int progressMax() = 0;", progressSink, StringComparison.Ordinal);
        Assert.Contains("virtual void onProgressEvent(const ProgressEvent& progressEvent) = 0;", progressSink, StringComparison.Ordinal);

        Assert.Contains("class HashEngineObserver: public HashProgressSink", observer, StringComparison.Ordinal);
        Assert.Contains("virtual void onProgressEvent(const ProgressEvent& progressEvent)", observer, StringComparison.Ordinal);
        Assert.Contains("virtual void onJobPreparing() = 0;", observer, StringComparison.Ordinal);
        Assert.Contains("virtual void onJobPreparationFinished() = 0;", observer, StringComparison.Ordinal);
        Assert.Contains("virtual void onJobCancelled() = 0;", observer, StringComparison.Ordinal);
        Assert.Contains("virtual void onJobCompleted() = 0;", observer, StringComparison.Ordinal);
        Assert.Contains("virtual void onFileResultEvent(const HashResult& result,", observer, StringComparison.Ordinal);
        Assert.Contains("virtual int queryProgressMax() = 0;", observer, StringComparison.Ordinal);
        Assert.Contains("virtual void onTotalProgressValue(int value) = 0;", observer, StringComparison.Ordinal);
        Assert.Contains("onFileResultEvent(progressEvent.result, progressEvent.type, progressEvent.uppercaseDigest);", observer, StringComparison.Ordinal);
        Assert.Contains("onTotalProgressValue(progressEvent.value);", observer, StringComparison.Ordinal);
        Assert.DoesNotContain("virtual void showFileName(const HashResult& result) = 0;", observer, StringComparison.Ordinal);
        Assert.DoesNotContain("virtual void updateProgWhole(int value) = 0;", observer, StringComparison.Ordinal);
        Assert.DoesNotContain("CreateCompatibilityResultData(result);", observer, StringComparison.Ordinal);
        Assert.False(File.Exists(legacyObserverPath));
        Assert.False(File.Exists(legacyBridgePath));
        Assert.False(File.Exists(legacyUiBridgeBasePath));
    }

    [Fact]
    public void HashEngine_StartsFromHashRequest_AndEmitsProgressEvents()
    {
        string global = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\Global.h");
        string executionContext = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashExecutionContext.h");
        string threadExecutionAccess = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\ThreadDataExecutionAccess.h");
        string engineHeader = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashEngine.h");
        string threadEntryHeader = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashThreadEntry.h");
        string engine = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashEngine.cpp");
        string threadEntry = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashThreadEntry.cpp");
        string threadEntryProjection = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashThreadEntryProjection.h");
        string fileRunner = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashFileRunner.cpp");
        string digestQueue = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashDigestQueue.cpp");
        string digestPipeline = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashDigestPipeline.cpp");
        string digestExecution = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashDigestExecution.cpp");
        string digestExecutionHeader = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashDigestExecution.h");
        string digestContextOps = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashDigestContextOps.cpp");
        string digestContextOpsHeader = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashDigestContextOps.h");
        string digestOperationRegistry = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashDigestOperationRegistry.cpp");
        string digestOperationRegistryHeader = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashDigestOperationRegistry.h");
        string digestLifecycle = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashDigestLifecycle.cpp");
        string digestLifecycleHeader = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashDigestLifecycle.h");
        string digestRuntimePlan = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashDigestRuntimePlan.cpp");
        string digestRuntimePlanHeader = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashDigestRuntimePlan.h");
        string digestCompletion = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashDigestCompletion.cpp");
        string digestCompletionHeader = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashDigestCompletion.h");
        string digestExecutionMode = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashDigestExecutionMode.cpp");
        string digestExecutionModeHeader = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashDigestExecutionMode.h");
        string digestBufferPlan = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashDigestBufferPlan.cpp");
        string digestBufferPlanHeader = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashDigestBufferPlan.h");
        string digestQueueHeader = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashDigestQueue.h");
        string digestQueuePlan = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashDigestQueuePlan.cpp");
        string digestQueuePlanHeader = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashDigestQueuePlan.h");
        string digestSinglePass = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashDigestSinglePass.cpp");
        string digestUpdater = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashDigestUpdater.cpp");
        string digestUpdaterHeader = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashDigestUpdater.h");
        string fileAttemptWorkflow = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashFileAttemptWorkflow.cpp");
        string fileAttemptCompletionWorkflow = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashFileAttemptCompletionWorkflow.cpp");
        string fileAttemptCompletionWorkflowHeader = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashFileAttemptCompletionWorkflow.h");
        string fileResultWorkflow = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashFileResultWorkflow.cpp");
        string fileResultWorkflowHeader = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashFileResultWorkflow.h");
        string fileAttemptStateOps = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashFileAttemptStateOps.cpp");
        string fileAttemptStateOpsHeader = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashFileAttemptStateOps.h");
        string fileSizeAccounting = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashFileSizeAccounting.cpp");
        string fileSizeAccountingHeader = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashFileSizeAccounting.h");
        string jobExecutionPlan = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashJobExecutionPlan.cpp");
        string jobExecutionPlanHeader = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashJobExecutionPlan.h");
        string jobLifecycleWorkflow = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashJobLifecycleWorkflow.cpp");
        string jobLifecycleWorkflowHeader = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashJobLifecycleWorkflow.h");
        string preScanSizeProbe = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashPreScanSizeProbe.cpp");
        string preScanSizeProbeHeader = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashPreScanSizeProbe.h");
        string preScanSizeAccounting = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashPreScanSizeAccounting.cpp");
        string preScanSizeAccountingHeader = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashPreScanSizeAccounting.h");
        string preScanWorkflow = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashPreScanWorkflow.cpp");
        string preScanWorkflowHeader = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashPreScanWorkflow.h");
        string preparationWorkflow = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashPreparationWorkflow.cpp");
        string preparationWorkflowHeader = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashPreparationWorkflow.h");
        string progressTracker = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashProgressTracker.cpp");
        string scheduler = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashScheduler.cpp");
        string schedulerPlan = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashSchedulerPlan.cpp");
        string schedulerPlanHeader = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashSchedulerPlan.h");
        string schedulerDispatch = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashSchedulerDispatch.cpp");
        string preparation = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashEnginePreparation.cpp");
        string preparationPlan = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashPreparationPlan.cpp");
        string preparationPlanHeader = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashPreparationPlan.h");
        string result = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashEngineResult.cpp");
        string fileVersionResolver = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashFileVersionResolver.cpp");
        string fileVersionResolverHeader = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashFileVersionResolver.h");
        string publisher = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashResultPublisher.cpp");
        string successfulFileCompletionWorkflow = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashSuccessfulFileCompletionWorkflow.cpp");
        string successfulFileCompletionWorkflowHeader = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashSuccessfulFileCompletionWorkflow.h");
        string errorResultWorkflow = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashErrorResultWorkflow.cpp");
        string errorResultWorkflowHeader = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashErrorResultWorkflow.h");
        string resultEventWorkflow = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashResultEventWorkflow.cpp");
        string resultEventWorkflowHeader = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashResultEventWorkflow.h");
        string internalHeader = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\HashEngineInternal.h");

        Assert.Contains("class HashProgressSink;", global, StringComparison.Ordinal);
        Assert.Contains("HashProgressSink *observer;", global, StringComparison.Ordinal);
        Assert.Contains("struct HashExecutionPreferenceState", global, StringComparison.Ordinal);
        Assert.Contains("struct HashCancellationState", global, StringComparison.Ordinal);
        Assert.Contains("struct HashJobState", global, StringComparison.Ordinal);
        Assert.Contains("std::atomic<bool> stopRequested;", global, StringComparison.Ordinal);
        Assert.Contains("std::atomic<bool> working;", global, StringComparison.Ordinal);
        Assert.Contains("HashJobState jobState;", global, StringComparison.Ordinal);
        Assert.Contains("std::vector<bool> enabled;", global, StringComparison.Ordinal);
        Assert.Contains("struct HashExecutionContext", executionContext, StringComparison.Ordinal);
        Assert.Contains("CreateHashExecutionContext(HashProgressSink *progressSink, HashJobState& jobState, HashCancellationState& cancellationState)", executionContext, StringComparison.Ordinal);
        Assert.DoesNotContain("CreateHashExecutionContext(ThreadData& threadData)", executionContext, StringComparison.Ordinal);
        Assert.Contains("GetHashExecutionProgressSink(const HashExecutionContext& executionContext)", executionContext, StringComparison.Ordinal);
        Assert.Contains("ShouldStopHashExecution(const HashExecutionContext& executionContext)", executionContext, StringComparison.Ordinal);
        Assert.Contains("AppendHashExecutionResult(HashExecutionContext& executionContext)", executionContext, StringComparison.Ordinal);
        Assert.Contains("HashJobState& jobState;", executionContext, StringComparison.Ordinal);
        Assert.Contains("HashCancellationState& cancellationState;", executionContext, StringComparison.Ordinal);
        Assert.Contains("HashExecutionContext(HashProgressSink *sink, HashJobState& state, HashCancellationState& cancellation)", executionContext, StringComparison.Ordinal);
        Assert.Contains("SetThreadDataObserver(ThreadData& threadData, HashProgressSink *observer)", threadExecutionAccess, StringComparison.Ordinal);
        Assert.Contains("GetThreadDataObserver(const ThreadData& threadData)", threadExecutionAccess, StringComparison.Ordinal);
        Assert.Contains("GetThreadDataHashExecutionPreferenceState(const ThreadData& threadData)", threadExecutionAccess, StringComparison.Ordinal);
        Assert.Contains("GetThreadDataHashCancellationState(const ThreadData& threadData)", threadExecutionAccess, StringComparison.Ordinal);
        Assert.Contains("GetThreadDataHashJobState(const ThreadData& threadData)", threadExecutionAccess, StringComparison.Ordinal);
        Assert.Contains("struct HashExecutionContext;", engineHeader, StringComparison.Ordinal);
        Assert.Contains("int RunHashRequest(HashExecutionContext *executionContext, const HashRequest& request);", engineHeader, StringComparison.Ordinal);
        Assert.DoesNotContain("int WINAPI HashThreadFunc(void *param);", engineHeader, StringComparison.Ordinal);
        Assert.Contains("int WINAPI HashThreadFunc(void *param);", threadEntryHeader, StringComparison.Ordinal);
        Assert.Contains("int RunHashRequest(HashExecutionContext *executionContext, const HashRequest& request)", engine, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashThreadEntry.h\"", threadEntry, StringComparison.Ordinal);
        Assert.DoesNotContain("#include \"Common/HashRequestProjection.h\"", engine, StringComparison.Ordinal);
        Assert.DoesNotContain("#include \"Common/ThreadDataExecutionAccess.h\"", engine, StringComparison.Ordinal);
        Assert.DoesNotContain("HashRequest request = CreateHashRequest(*thrdData);", engine, StringComparison.Ordinal);
        Assert.DoesNotContain("HashExecutionContext executionContext = CreateHashExecutionContext(", engine, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashThreadEntryProjection.h\"", threadEntry, StringComparison.Ordinal);
        Assert.DoesNotContain("#include \"Common/HashRequestProjection.h\"", threadEntry, StringComparison.Ordinal);
        Assert.DoesNotContain("#include \"Common/ThreadDataExecutionAccess.h\"", threadEntry, StringComparison.Ordinal);
        Assert.Contains("HashRequest request = CreateThreadDataHashRequest(*thrdData);", threadEntry, StringComparison.Ordinal);
        Assert.Contains("HashExecutionContext executionContext = CreateThreadDataHashExecutionContext(*thrdData);", threadEntry, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashExecutionContext.h\"", threadEntryProjection, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashRequestProjection.h\"", threadEntryProjection, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/ThreadDataExecutionAccess.h\"", threadEntryProjection, StringComparison.Ordinal);
        Assert.Contains("CreateThreadDataHashExecutionContext(ThreadData& threadData)", threadEntryProjection, StringComparison.Ordinal);
        Assert.Contains("CreateThreadDataHashRequest(const ThreadData& threadData)", threadEntryProjection, StringComparison.Ordinal);
        Assert.Contains("GetThreadDataObserver(threadData)", threadEntryProjection, StringComparison.Ordinal);
        Assert.Contains("GetMutableThreadDataHashJobState(threadData)", threadEntryProjection, StringComparison.Ordinal);
        Assert.Contains("GetMutableThreadDataHashCancellationState(threadData)", threadEntryProjection, StringComparison.Ordinal);
        Assert.Contains("CreateHashRequest(threadData)", threadEntryProjection, StringComparison.Ordinal);
        Assert.Contains("return RunHashRequest(&executionContext, request);", threadEntry, StringComparison.Ordinal);
        Assert.Contains("InitializeHashJobExecutionPlan(request, &executionPlan);", engine, StringComparison.Ordinal);
        Assert.Contains("ULLongVector fSizes(GetHashRequestFileCount(request));", engine, StringComparison.Ordinal);
        Assert.Contains("RunHashScheduler(executionContext, request, executionPlan, isSizeCaled, fSizes)", engine, StringComparison.Ordinal);
        Assert.Contains("ResetHashExecutionTotalSize(*executionContext);", engine, StringComparison.Ordinal);
        Assert.Contains("ExecuteCancelledHashingWorkflow(executionContext, observer);", engine, StringComparison.Ordinal);
        Assert.Contains("ExecuteCompletedHashingWorkflow(executionContext, observer);", engine, StringComparison.Ordinal);
        Assert.DoesNotContain("FileExecutionState executionState = { 0 };", engine, StringComparison.Ordinal);
        Assert.DoesNotContain("static bool ProcessOpenedFileHashing(", engine, StringComparison.Ordinal);

        Assert.Contains("bool RunHashScheduler(HashExecutionContext *executionContext, const HashRequest& request, const HashJobExecutionPlan& executionPlan, bool isSizeCaled, ULLongVector& fSizes)", scheduler, StringComparison.Ordinal);
        Assert.Contains("executionState.executionPlan = executionPlan;", scheduler, StringComparison.Ordinal);
        Assert.Contains("ExecuteScheduledHashRequestFiles(executionContext, request, isSizeCaled, fSizes, &executionState", scheduler, StringComparison.Ordinal);
        Assert.Contains("FileExecutionState executionState = { 0 };", scheduler, StringComparison.Ordinal);
        Assert.Contains("const HashSchedulerPlan& schedulerPlan = GetHashJobSchedulerPlan(executionState.executionPlan);", scheduler, StringComparison.Ordinal);
        Assert.Contains("ThreadPool threadPool(GetHashSchedulerWorkerThreadCount(schedulerPlan));", scheduler, StringComparison.Ordinal);
        Assert.Contains("bool ExecuteScheduledHashRequestFiles(HashExecutionContext *executionContext, const HashRequest& request, bool isSizeCaled, ULLongVector& fSizes, FileExecutionState *executionState", schedulerDispatch, StringComparison.Ordinal);
        Assert.Contains("VisitHashRequestFiles(request", schedulerDispatch, StringComparison.Ordinal);
        Assert.Contains("RunFileHashAttempt(executionContext, request, fileIndex, fullPath, isSizeCaled, fSizes", schedulerDispatch, StringComparison.Ordinal);

        Assert.Contains("bool RunFileHashAttempt(HashExecutionContext *executionContext, const HashRequest& request, uint32_t fileIndex, const tstring& fullPath", fileRunner, StringComparison.Ordinal);
        Assert.Contains("ExecuteFileHashAttemptWorkflow(executionContext, request, fileIndex, fullPath, isSizeCaled, fSizes, executionState", fileRunner, StringComparison.Ordinal);
        Assert.DoesNotContain("FileExecutionState executionState = { 0 };", fileRunner, StringComparison.Ordinal);
        Assert.Contains("bool ExecuteFileHashAttemptWorkflow(HashExecutionContext *executionContext, const HashRequest& request, uint32_t fileIndex, const sunjwbase::tstring& fullPath", fileAttemptWorkflow, StringComparison.Ordinal);
        Assert.Contains("YieldHashThread();", fileAttemptWorkflow, StringComparison.Ordinal);
        Assert.Contains("ShouldStopHashExecution(*executionContext)", fileAttemptWorkflow, StringComparison.Ordinal);
        Assert.Contains("bool wasStopped = ProcessOpenedFileHashing(executionContext, request, result, fileIndex, isSizeCaled, fSizes, executionState", fileAttemptWorkflow, StringComparison.Ordinal);
        Assert.Contains("CompleteFileAttempt(executionContext, request, result, fileIndex, isSizeCaled, *executionState);", fileAttemptWorkflow, StringComparison.Ordinal);
        Assert.Contains("struct FileAttemptState;", fileAttemptStateOpsHeader, StringComparison.Ordinal);
        Assert.Contains("struct FileProgressState;", fileAttemptStateOpsHeader, StringComparison.Ordinal);
        Assert.Contains("void InitializeFileAttemptState(const TCHAR *path, sunjwbase::OsFile *osFile, FileAttemptState *fileAttemptState);", fileAttemptStateOpsHeader, StringComparison.Ordinal);
        Assert.Contains("bool OpenFileForHashing(FileAttemptState *fileAttemptState, void *openErrorBuffer);", fileAttemptStateOpsHeader, StringComparison.Ordinal);
        Assert.Contains("void ResetFileProgressState(FileProgressState *progressState);", fileAttemptStateOpsHeader, StringComparison.Ordinal);
        Assert.Contains("void InitializeFileAttemptState(const TCHAR *path, sunjwbase::OsFile *osFile, FileAttemptState *fileAttemptState)", fileAttemptStateOps, StringComparison.Ordinal);
        Assert.Contains("fileAttemptState->path = path;", fileAttemptStateOps, StringComparison.Ordinal);
        Assert.Contains("fileAttemptState->osFile = osFile;", fileAttemptStateOps, StringComparison.Ordinal);
        Assert.Contains("fileAttemptState->fileVersion.clear();", fileAttemptStateOps, StringComparison.Ordinal);
        Assert.Contains("fileAttemptState->isFileOpened = fileAttemptState->osFile->openReadScan(openErrorBuffer);", fileAttemptStateOps, StringComparison.Ordinal);
        Assert.Contains("void ResetFileProgressState(FileProgressState *progressState)", fileAttemptStateOps, StringComparison.Ordinal);
        Assert.Contains("progressState->finishedSize = 0;", fileAttemptStateOps, StringComparison.Ordinal);
        Assert.Contains("progressState->position = 0;", fileAttemptStateOps, StringComparison.Ordinal);
        Assert.Contains("bool ProcessOpenedFileHashing(HashExecutionContext *executionContext, const HashRequest& request, HashResult& result, uint32_t fileIndex,", digestPipeline, StringComparison.Ordinal);
        Assert.Contains("HashDigestRuntimePlan digestRuntimePlan = CreateHashDigestRuntimePlan(executionState->executionPlan);", digestPipeline, StringComparison.Ordinal);
        Assert.Contains("unsigned int preferredBufferLength = GetHashDigestRuntimePreferredBufferLength(digestRuntimePlan);", digestPipeline, StringComparison.Ordinal);
        Assert.Contains("bool ExecuteOpenedFileDigestUpdate(HashExecutionContext *executionContext, const HashDigestRuntimePlan& digestRuntimePlan, uint64_t fsize, bool isSizeCaled,", digestExecutionHeader, StringComparison.Ordinal);
        Assert.Contains("bool ExecuteOpenedFileDigestUpdate(HashExecutionContext *executionContext, const HashDigestRuntimePlan& digestRuntimePlan, uint64_t fsize, bool isSizeCaled,", digestExecution, StringComparison.Ordinal);
        Assert.Contains("const DigestUpdateRequest& digestUpdateRequest = GetHashDigestRuntimeUpdateRequest(digestRuntimePlan);", digestExecution, StringComparison.Ordinal);
        Assert.Contains("const HashDigestQueuePlan& digestQueuePlan = GetHashDigestRuntimeQueuePlan(digestRuntimePlan);", digestExecution, StringComparison.Ordinal);
        Assert.Contains("if (IsParallelHashDigestExecutionMode(digestExecutionMode))", digestExecution, StringComparison.Ordinal);
        Assert.Contains("bool ProcessOpenedFileHashingParallel(HashExecutionContext *executionContext, const DigestUpdateRequest& digestUpdateRequest, uint64_t fileSize, bool isSizeCaled,", digestQueue, StringComparison.Ordinal);
        Assert.Contains("const HashDigestQueuePlan& digestQueuePlan", digestQueue, StringComparison.Ordinal);
        Assert.Contains("bool ProcessOpenedFileHashingSinglePass(HashExecutionContext *executionContext, const DigestUpdateRequest& digestUpdateRequest, uint64_t fsize, bool isSizeCaled,", digestSinglePass, StringComparison.Ordinal);
        Assert.Contains("bool ReadDigestDataBuffer(FileExecutionState *executionState, DigestDataBuffer& dataBuffer)", digestQueue, StringComparison.Ordinal);
        Assert.Contains("unsigned int NormalizeDigestDataBufferPreferredLength(unsigned int preferredLength);", digestQueueHeader, StringComparison.Ordinal);
        Assert.Contains("unsigned int NormalizeDigestDataBufferPreferredLength(unsigned int preferredLength)", digestQueue, StringComparison.Ordinal);
        Assert.Contains("uint64_t CalculateFileChunkIterations(uint64_t fileSize, unsigned int preferredLength)", digestQueue, StringComparison.Ordinal);
        Assert.DoesNotContain("static unsigned int preflen;", digestQueueHeader, StringComparison.Ordinal);
        Assert.DoesNotContain("void SetDigestDataBufferPreferredLength(unsigned int preferredLength);", digestQueueHeader, StringComparison.Ordinal);
        Assert.Contains("UpdateDigestContextsParallel(digestUpdateRequest", digestQueue, StringComparison.Ordinal);
        Assert.Contains("UpdateDigestContextsParallel(digestUpdateRequest", digestQueue, StringComparison.Ordinal);
        Assert.Contains("queueDataBuffer.size() < GetHashDigestQueueMaxBufferedChunkCount(digestQueuePlan)", digestQueue, StringComparison.Ordinal);
        Assert.Contains("ExecuteOpenedFileDigestUpdate(executionContext, digestRuntimePlan, fsize, isSizeCaled, executionState", digestPipeline, StringComparison.Ordinal);
        Assert.Contains("UpdateDigestContextsSequential(digestUpdateRequest", digestSinglePass, StringComparison.Ordinal);
        Assert.Contains("struct FileHashContexts;", digestLifecycleHeader, StringComparison.Ordinal);
        Assert.Contains("void InitializeFileHashing(const HashRequest& request, HashExecutionContext *executionContext, FileHashContexts *hashContexts);", digestLifecycleHeader, StringComparison.Ordinal);
        Assert.Contains("void FinalizeDigestStrings(const HashRequest& request, FileHashContexts& hashContexts, ResultDigestStorage& digestBundle);", digestLifecycleHeader, StringComparison.Ordinal);
        Assert.Contains("void InitializeFileHashing(const HashRequest& request, HashExecutionContext *executionContext, FileHashContexts *hashContexts)", digestLifecycle, StringComparison.Ordinal);
        Assert.Contains("void FinalizeDigestStrings(const HashRequest& request, FileHashContexts& hashContexts, ResultDigestStorage& digestBundle)", digestLifecycle, StringComparison.Ordinal);
        Assert.Contains("void InitializeHashDigestContext(FileHashContexts *hashContexts, ResultDigestType digestType);", digestContextOpsHeader, StringComparison.Ordinal);
        Assert.Contains("void FinalizeHashDigestContext(FileHashContexts& hashContexts, ResultDigestType digestType, ResultDigestStorage& digestBundle);", digestContextOpsHeader, StringComparison.Ordinal);
        Assert.Contains("void InitializeHashDigestContext(FileHashContexts *hashContexts, ResultDigestType digestType)", digestContextOps, StringComparison.Ordinal);
        Assert.Contains("void FinalizeHashDigestContext(FileHashContexts& hashContexts, ResultDigestType digestType, ResultDigestStorage& digestBundle)", digestContextOps, StringComparison.Ordinal);
        Assert.Contains("TryGetHashDigestOperationDescriptor(digestType, &operationDescriptor)", digestContextOps, StringComparison.Ordinal);
        Assert.Contains("struct HashDigestOperationDescriptor", digestOperationRegistryHeader, StringComparison.Ordinal);
        Assert.Contains("TryGetHashDigestOperationDescriptor(ResultDigestType digestType, HashDigestOperationDescriptor *operationDescriptor);", digestOperationRegistryHeader, StringComparison.Ordinal);
        Assert.Contains("bool IsHashDigestOperationDescriptorComplete(const HashDigestOperationDescriptor& operationDescriptor);", digestOperationRegistryHeader, StringComparison.Ordinal);
        Assert.Contains("bool IsHashDigestOperationDescriptorSupported(ResultDigestType digestType);", digestOperationRegistryHeader, StringComparison.Ordinal);
        Assert.Contains("bool IsHashDigestOperationRegistryConsistent();", digestOperationRegistryHeader, StringComparison.Ordinal);
        Assert.Contains("static const HashDigestOperationDescriptor operationDescriptors[]", digestOperationRegistry, StringComparison.Ordinal);
        Assert.Contains("InitializeHashDigestContext(hashContexts, digestType);", digestLifecycle, StringComparison.Ordinal);
        Assert.Contains("FinalizeHashDigestContext(hashContexts, digestType, digestBundle);", digestLifecycle, StringComparison.Ordinal);
        Assert.DoesNotContain("switch (digestType)", digestLifecycle, StringComparison.Ordinal);
        Assert.Contains("DigestUpdateRequest CreateDigestUpdateRequest(const HashRequest& request)", digestUpdater, StringComparison.Ordinal);
        Assert.DoesNotContain("std::vector<ResultDigestType> algorithms;", digestUpdaterHeader, StringComparison.Ordinal);
        Assert.DoesNotContain("VisitDigestUpdateRequestAlgorithms(const DigestUpdateRequest& digestUpdateRequest", digestUpdaterHeader, StringComparison.Ordinal);
        Assert.Contains("VisitRegisteredHashAlgorithms([&](int index, const HashAlgorithmDescriptor& algorithmDescriptor)", digestUpdater, StringComparison.Ordinal);
        Assert.Contains("if (!HasHashRequestAlgorithm(request, digestType))", digestUpdater, StringComparison.Ordinal);
        Assert.Contains("if (!IsHashDigestOperationRegistryConsistent())", digestUpdater, StringComparison.Ordinal);
        Assert.Contains("TryResolveDigestUpdateOperationDescriptor(digestType, &operationDescriptor)", digestUpdater, StringComparison.Ordinal);
        Assert.DoesNotContain("digestUpdateRequest.algorithms.push_back(digestType);", digestUpdater, StringComparison.Ordinal);
        Assert.Contains("enum HashDigestExecutionMode", digestExecutionModeHeader, StringComparison.Ordinal);
        Assert.Contains("HashDigestExecutionMode ResolveHashDigestExecutionMode(const HashRequest& request);", digestExecutionModeHeader, StringComparison.Ordinal);
        Assert.Contains("bool IsParallelHashDigestExecutionMode(HashDigestExecutionMode executionMode);", digestExecutionModeHeader, StringComparison.Ordinal);
        Assert.Contains("HashDigestExecutionMode ResolveHashDigestExecutionMode(const HashRequest& request)", digestExecutionMode, StringComparison.Ordinal);
        Assert.Contains("return HASH_DIGEST_EXECUTION_MODE_PARALLEL;", digestExecutionMode, StringComparison.Ordinal);
        Assert.Contains("struct HashDigestBufferPlan", digestBufferPlanHeader, StringComparison.Ordinal);
        Assert.Contains("unsigned int preferredBufferLength;", digestBufferPlanHeader, StringComparison.Ordinal);
        Assert.Contains("HashDigestBufferPlan CreateHashDigestBufferPlan(const HashRequest& request, HashDigestExecutionMode digestExecutionMode);", digestBufferPlanHeader, StringComparison.Ordinal);
        Assert.Contains("unsigned int GetHashDigestBufferPreferredLength(const HashDigestBufferPlan& digestBufferPlan);", digestBufferPlanHeader, StringComparison.Ordinal);
        Assert.Contains("HashDigestBufferPlan CreateHashDigestBufferPlan(const HashRequest& request, HashDigestExecutionMode digestExecutionMode)", digestBufferPlan, StringComparison.Ordinal);
        Assert.Contains("digestBufferPlan.preferredBufferLength = 1048576;", digestBufferPlan, StringComparison.Ordinal);
        Assert.Contains("unsigned int GetHashDigestBufferPreferredLength(const HashDigestBufferPlan& digestBufferPlan)", digestBufferPlan, StringComparison.Ordinal);
        Assert.Contains("struct HashDigestQueuePlan", digestQueuePlanHeader, StringComparison.Ordinal);
        Assert.Contains("size_t maxBufferedChunkCount;", digestQueuePlanHeader, StringComparison.Ordinal);
        Assert.Contains("HashDigestQueuePlan CreateHashDigestQueuePlan(const HashRequest& request, HashDigestExecutionMode digestExecutionMode);", digestQueuePlanHeader, StringComparison.Ordinal);
        Assert.Contains("size_t GetHashDigestQueueMaxBufferedChunkCount(const HashDigestQueuePlan& digestQueuePlan);", digestQueuePlanHeader, StringComparison.Ordinal);
        Assert.Contains("HashDigestQueuePlan CreateHashDigestQueuePlan(const HashRequest& request, HashDigestExecutionMode digestExecutionMode)", digestQueuePlan, StringComparison.Ordinal);
        Assert.Contains("digestQueuePlan.maxBufferedChunkCount = 4;", digestQueuePlan, StringComparison.Ordinal);
        Assert.Contains("size_t GetHashDigestQueueMaxBufferedChunkCount(const HashDigestQueuePlan& digestQueuePlan)", digestQueuePlan, StringComparison.Ordinal);
        Assert.Contains("struct HashJobExecutionPlan", jobExecutionPlanHeader, StringComparison.Ordinal);
        Assert.Contains("HashDigestExecutionMode digestExecutionMode;", jobExecutionPlanHeader, StringComparison.Ordinal);
        Assert.Contains("HashDigestBufferPlan digestBufferPlan;", jobExecutionPlanHeader, StringComparison.Ordinal);
        Assert.Contains("HashDigestQueuePlan digestQueuePlan;", jobExecutionPlanHeader, StringComparison.Ordinal);
        Assert.Contains("HashPreparationPlan preparationPlan;", jobExecutionPlanHeader, StringComparison.Ordinal);
        Assert.Contains("HashSchedulerPlan schedulerPlan;", jobExecutionPlanHeader, StringComparison.Ordinal);
        Assert.Contains("void InitializeHashJobExecutionPlan(const HashRequest& request, HashJobExecutionPlan *executionPlan);", jobExecutionPlanHeader, StringComparison.Ordinal);
        Assert.Contains("const DigestUpdateRequest& GetHashJobDigestUpdateRequest(const HashJobExecutionPlan& executionPlan);", jobExecutionPlanHeader, StringComparison.Ordinal);
        Assert.Contains("HashDigestExecutionMode GetHashJobDigestExecutionMode(const HashJobExecutionPlan& executionPlan);", jobExecutionPlanHeader, StringComparison.Ordinal);
        Assert.Contains("const HashDigestBufferPlan& GetHashJobDigestBufferPlan(const HashJobExecutionPlan& executionPlan);", jobExecutionPlanHeader, StringComparison.Ordinal);
        Assert.Contains("const HashDigestQueuePlan& GetHashJobDigestQueuePlan(const HashJobExecutionPlan& executionPlan);", jobExecutionPlanHeader, StringComparison.Ordinal);
        Assert.Contains("const HashPreparationPlan& GetHashJobPreparationPlan(const HashJobExecutionPlan& executionPlan);", jobExecutionPlanHeader, StringComparison.Ordinal);
        Assert.Contains("const HashSchedulerPlan& GetHashJobSchedulerPlan(const HashJobExecutionPlan& executionPlan);", jobExecutionPlanHeader, StringComparison.Ordinal);
        Assert.Contains("executionPlan->digestUpdateRequest = CreateDigestUpdateRequest(request);", jobExecutionPlan, StringComparison.Ordinal);
        Assert.Contains("executionPlan->digestExecutionMode = ResolveHashDigestExecutionMode(request);", jobExecutionPlan, StringComparison.Ordinal);
        Assert.Contains("executionPlan->digestBufferPlan = CreateHashDigestBufferPlan(request, executionPlan->digestExecutionMode);", jobExecutionPlan, StringComparison.Ordinal);
        Assert.Contains("executionPlan->digestQueuePlan = CreateHashDigestQueuePlan(request, executionPlan->digestExecutionMode);", jobExecutionPlan, StringComparison.Ordinal);
        Assert.Contains("executionPlan->preparationPlan = CreateHashPreparationPlan(request);", jobExecutionPlan, StringComparison.Ordinal);
        Assert.Contains("executionPlan->schedulerPlan = CreateHashSchedulerPlan(request, executionPlan->digestExecutionMode);", jobExecutionPlan, StringComparison.Ordinal);
        Assert.Contains("return executionPlan.digestUpdateRequest;", jobExecutionPlan, StringComparison.Ordinal);
        Assert.Contains("return executionPlan.digestExecutionMode;", jobExecutionPlan, StringComparison.Ordinal);
        Assert.Contains("return executionPlan.digestBufferPlan;", jobExecutionPlan, StringComparison.Ordinal);
        Assert.Contains("return executionPlan.digestQueuePlan;", jobExecutionPlan, StringComparison.Ordinal);
        Assert.Contains("return executionPlan.preparationPlan;", jobExecutionPlan, StringComparison.Ordinal);
        Assert.Contains("return executionPlan.schedulerPlan;", jobExecutionPlan, StringComparison.Ordinal);
        Assert.Contains("struct HashPreparationPlan", preparationPlanHeader, StringComparison.Ordinal);
        Assert.Contains("size_t preScanFileCountThreshold;", preparationPlanHeader, StringComparison.Ordinal);
        Assert.Contains("HashPreparationPlan CreateHashPreparationPlan(const HashRequest& request);", preparationPlanHeader, StringComparison.Ordinal);
        Assert.Contains("bool ShouldPreScanHashRequestFileSizes(const HashPreparationPlan& preparationPlan, const HashRequest& request);", preparationPlanHeader, StringComparison.Ordinal);
        Assert.Contains("HashPreparationPlan CreateHashPreparationPlan(const HashRequest& request)", preparationPlan, StringComparison.Ordinal);
        Assert.Contains("preparationPlan.preScanFileCountThreshold = 200;", preparationPlan, StringComparison.Ordinal);
        Assert.Contains("bool ShouldPreScanHashRequestFileSizes(const HashPreparationPlan& preparationPlan, const HashRequest& request)", preparationPlan, StringComparison.Ordinal);
        Assert.Contains("void ExecuteCancelledHashingWorkflow(HashExecutionContext *executionContext, HashProgressSink *observer);", jobLifecycleWorkflowHeader, StringComparison.Ordinal);
        Assert.Contains("void ExecuteCompletedHashingWorkflow(HashExecutionContext *executionContext, HashProgressSink *observer);", jobLifecycleWorkflowHeader, StringComparison.Ordinal);
        Assert.Contains("void ExecuteCancelledHashingWorkflow(HashExecutionContext *executionContext, HashProgressSink *observer)", jobLifecycleWorkflow, StringComparison.Ordinal);
        Assert.Contains("void ExecuteCompletedHashingWorkflow(HashExecutionContext *executionContext, HashProgressSink *observer)", jobLifecycleWorkflow, StringComparison.Ordinal);
        Assert.Contains("observer->onProgressEvent(CreateCancelledProgressEvent());", jobLifecycleWorkflow, StringComparison.Ordinal);
        Assert.Contains("observer->onProgressEvent(CreateCompletedProgressEvent());", jobLifecycleWorkflow, StringComparison.Ordinal);
        Assert.Contains("SetHashExecutionWorking(*executionContext, false);", jobLifecycleWorkflow, StringComparison.Ordinal);
        Assert.Contains("struct HashSchedulerPlan", schedulerPlanHeader, StringComparison.Ordinal);
        Assert.Contains("size_t workerThreadCount;", schedulerPlanHeader, StringComparison.Ordinal);
        Assert.Contains("HashSchedulerPlan CreateHashSchedulerPlan(const HashRequest& request, HashDigestExecutionMode digestExecutionMode);", schedulerPlanHeader, StringComparison.Ordinal);
        Assert.Contains("size_t GetHashSchedulerWorkerThreadCount(const HashSchedulerPlan& schedulerPlan);", schedulerPlanHeader, StringComparison.Ordinal);
        Assert.Contains("HashSchedulerPlan CreateHashSchedulerPlan(const HashRequest& request, HashDigestExecutionMode digestExecutionMode)", schedulerPlan, StringComparison.Ordinal);
        Assert.Contains("schedulerPlan.workerThreadCount = 5;", schedulerPlan, StringComparison.Ordinal);
        Assert.Contains("size_t GetHashSchedulerWorkerThreadCount(const HashSchedulerPlan& schedulerPlan)", schedulerPlan, StringComparison.Ordinal);
        Assert.Contains("CreateHashDigestRuntimePlan(executionState->executionPlan)", digestPipeline, StringComparison.Ordinal);
        Assert.Contains("GetHashDigestRuntimeUpdateRequest(digestRuntimePlan)", digestExecution, StringComparison.Ordinal);
        Assert.Contains("GetHashDigestRuntimeExecutionMode(digestRuntimePlan)", digestExecution, StringComparison.Ordinal);
        Assert.Contains("GetHashDigestRuntimePreferredBufferLength(digestRuntimePlan)", digestExecution, StringComparison.Ordinal);
        Assert.Contains("GetHashDigestRuntimeQueuePlan(digestRuntimePlan)", digestExecution, StringComparison.Ordinal);
        Assert.Contains("std::vector<HashDigestOperationDescriptor> operationDescriptors;", digestUpdaterHeader, StringComparison.Ordinal);
        Assert.Contains("VisitDigestUpdateRequestOperations(const DigestUpdateRequest& digestUpdateRequest", digestUpdaterHeader, StringComparison.Ordinal);
        Assert.Contains("VisitDigestUpdateRequestOperations(digestUpdateRequest, [&](const HashDigestOperationDescriptor& operationDescriptor)", digestUpdater, StringComparison.Ordinal);
        Assert.DoesNotContain("DigestUpdateRequest digestUpdateRequest = { 0 };", digestUpdater, StringComparison.Ordinal);
        Assert.DoesNotContain("static const DigestUpdateRequest emptyDigestUpdateRequest = { 0 };", digestRuntimePlan, StringComparison.Ordinal);
        Assert.DoesNotContain("static const HashDigestQueuePlan fallbackQueuePlan = { 1 };", digestRuntimePlan, StringComparison.Ordinal);
        Assert.DoesNotContain("HashJobExecutionPlan executionPlan = { 0 };", engine, StringComparison.Ordinal);
        Assert.Contains("void UpdateDigestContextsParallel(const DigestUpdateRequest& digestUpdateRequest", digestUpdater, StringComparison.Ordinal);
        Assert.Contains("std::vector<std::future<void>> digestUpdateTasks;", digestUpdater, StringComparison.Ordinal);
        Assert.Contains("digestUpdateTasks.push_back(threadPool->enqueue([&hashContexts, data, dataLen, operationDescriptor]()", digestUpdater, StringComparison.Ordinal);
        Assert.Contains("void UpdateHashExecutionProgress(HashExecutionContext *executionContext, uint64_t fileSize, bool isSizeCaled, unsigned int dataLen,", progressTracker, StringComparison.Ordinal);
        Assert.Contains("observer->onProgressEvent(CreateFileProgressEvent(positionNew));", progressTracker, StringComparison.Ordinal);
        Assert.Contains("observer->onProgressEvent(CreateTotalProgressEvent(progressState->positionWhole));", progressTracker, StringComparison.Ordinal);
        Assert.Contains("UpdateHashExecutionProgress(executionContext, fileSize, isSizeCaled, ptrDataBufCalc->datalen, &executionState->progressState);", digestQueue, StringComparison.Ordinal);
        Assert.Contains("UpdateHashExecutionProgress(executionContext, fsize, isSizeCaled, databuf.datalen, &executionState->progressState);", digestSinglePass, StringComparison.Ordinal);

        Assert.Contains("PrepareHashingWork(HashExecutionContext *executionContext, const HashRequest& request, const HashPreparationPlan& preparationPlan", preparation, StringComparison.Ordinal);
        Assert.Contains("TryPreScanSmallBatchFileSizes(HashExecutionContext *executionContext, const HashRequest& request, const HashPreparationPlan& preparationPlan", preparation, StringComparison.Ordinal);
        Assert.Contains("ShouldPreScanHashRequestFileSizes(preparationPlan, request)", preparation, StringComparison.Ordinal);
        Assert.Contains("uint64_t ResolveHashPreScannedFileSize(const TCHAR *path);", preScanSizeProbeHeader, StringComparison.Ordinal);
        Assert.Contains("uint64_t ResolveHashPreScannedFileSize(const TCHAR *path)", preScanSizeProbe, StringComparison.Ordinal);
        Assert.Contains("sunjwbase::OsFile osFile(path);", preScanSizeProbe, StringComparison.Ordinal);
        Assert.Contains("if (osFile.openRead())", preScanSizeProbe, StringComparison.Ordinal);
        Assert.Contains("fSize = osFile.getLength();", preScanSizeProbe, StringComparison.Ordinal);
        Assert.Contains("uint64_t TrackHashPreScannedFileSize(HashExecutionContext *executionContext, ULLongVector& fSizes, uint32_t fileIndex, uint64_t fSize);", preScanSizeAccountingHeader, StringComparison.Ordinal);
        Assert.Contains("uint64_t TrackHashPreScannedFileSize(HashExecutionContext *executionContext, ULLongVector& fSizes, uint32_t fileIndex, uint64_t fSize)", preScanSizeAccounting, StringComparison.Ordinal);
        Assert.Contains("fSizes[fileIndex] = fSize;", preScanSizeAccounting, StringComparison.Ordinal);
        Assert.Contains("AddHashExecutionTotalSize(*executionContext, fSize);", preScanSizeAccounting, StringComparison.Ordinal);
        Assert.Contains("void RunHashPreScanVisitWorkflow(HashExecutionContext *executionContext, const HashRequest& request, ULLongVector& fSizes, bool *wasCancelled);", preScanWorkflowHeader, StringComparison.Ordinal);
        Assert.Contains("void RunHashPreScanVisitWorkflow(HashExecutionContext *executionContext, const HashRequest& request, ULLongVector& fSizes, bool *wasCancelled)", preScanWorkflow, StringComparison.Ordinal);
        Assert.Contains("VisitHashRequestFiles(request, [&](uint32_t fileIndex, const tstring& fullPath)", preScanWorkflow, StringComparison.Ordinal);
        Assert.Contains("if (ShouldStopHashExecution(*executionContext))", preScanWorkflow, StringComparison.Ordinal);
        Assert.Contains("*wasCancelled = true;", preScanWorkflow, StringComparison.Ordinal);
        Assert.Contains("AccumulatePreScannedFileSize(executionContext, request, fSizes, fileIndex);", preScanWorkflow, StringComparison.Ordinal);
        Assert.Contains("bool ExecuteHashPreparationWorkflow(HashExecutionContext *executionContext, const HashRequest& request, const HashPreparationPlan& preparationPlan, ULLongVector& fSizes, bool *wasCancelled);", preparationWorkflowHeader, StringComparison.Ordinal);
        Assert.Contains("bool ExecuteHashPreparationWorkflow(HashExecutionContext *executionContext, const HashRequest& request, const HashPreparationPlan& preparationPlan, ULLongVector& fSizes, bool *wasCancelled)", preparationWorkflow, StringComparison.Ordinal);
        Assert.Contains("observer->onProgressEvent(CreatePreparingProgressEvent());", preparationWorkflow, StringComparison.Ordinal);
        Assert.Contains("bool isSizeCaled = TryPreScanSmallBatchFileSizes(executionContext, request, preparationPlan, fSizes, wasCancelled);", preparationWorkflow, StringComparison.Ordinal);
        Assert.Contains("if (*wasCancelled)", preparationWorkflow, StringComparison.Ordinal);
        Assert.Contains("observer->onProgressEvent(CreatePreparationFinishedProgressEvent());", preparationWorkflow, StringComparison.Ordinal);
        Assert.Contains("uint64_t fSize = ResolveHashPreScannedFileSize(path);", preparation, StringComparison.Ordinal);
        Assert.Contains("TrackHashPreScannedFileSize(executionContext, fSizes, fileIndex, fSize);", preparation, StringComparison.Ordinal);
        Assert.Contains("RunHashPreScanVisitWorkflow(executionContext, request, fSizes, wasCancelled);", preparation, StringComparison.Ordinal);
        Assert.Contains("return ExecuteHashPreparationWorkflow(executionContext, request, preparationPlan, fSizes, wasCancelled);", preparation, StringComparison.Ordinal);
        Assert.DoesNotContain("OsFile osFile(path);", preparation, StringComparison.Ordinal);
        Assert.DoesNotContain("fSizes[fileIndex] = fSize;", preparation, StringComparison.Ordinal);
        Assert.DoesNotContain("AddHashExecutionTotalSize(*executionContext, fSize);", preparation, StringComparison.Ordinal);
        Assert.DoesNotContain("VisitHashRequestFiles(request, [&](uint32_t fileIndex, const tstring& fullPath)", preparation, StringComparison.Ordinal);
        Assert.DoesNotContain("observer->onProgressEvent(CreatePreparingProgressEvent());", preparation, StringComparison.Ordinal);
        Assert.DoesNotContain("observer->onProgressEvent(CreatePreparationFinishedProgressEvent());", preparation, StringComparison.Ordinal);
        Assert.Contains("void PublishFilePathResult(HashExecutionContext *executionContext, HashResult& result);", fileResultWorkflowHeader, StringComparison.Ordinal);
        Assert.Contains("HashResult& ExecuteFileResultBeginWorkflow(HashExecutionContext *executionContext, const sunjwbase::tstring& path);", fileResultWorkflowHeader, StringComparison.Ordinal);
        Assert.Contains("HashResult& ExecuteFileHashAttemptBeginWorkflow(HashExecutionContext *executionContext, const sunjwbase::tstring& path, FileExecutionState *executionState, const TCHAR **resultPath);", fileResultWorkflowHeader, StringComparison.Ordinal);
        Assert.Contains("void PublishFilePathResult(HashExecutionContext *executionContext, HashResult& result)", fileResultWorkflow, StringComparison.Ordinal);
        Assert.Contains("HashResult& ExecuteFileResultBeginWorkflow(HashExecutionContext *executionContext, const sunjwbase::tstring& path)", fileResultWorkflow, StringComparison.Ordinal);
        Assert.Contains("HashResult& ExecuteFileHashAttemptBeginWorkflow(HashExecutionContext *executionContext, const sunjwbase::tstring& path, FileExecutionState *executionState, const TCHAR **resultPath)", fileResultWorkflow, StringComparison.Ordinal);
        Assert.Contains("AppendHashExecutionResult(*executionContext)", fileResultWorkflow, StringComparison.Ordinal);
        Assert.Contains("observer->onProgressEvent(CreateFileStartedProgressEvent(result));", fileResultWorkflow, StringComparison.Ordinal);
        Assert.Contains("EmitPathResult(executionContext, result);", fileResultWorkflow, StringComparison.Ordinal);
        Assert.Contains("return ExecuteFileResultBeginWorkflow(executionContext, path);", preparation, StringComparison.Ordinal);
        Assert.Contains("return ExecuteFileHashAttemptBeginWorkflow(executionContext, path, executionState, resultPath);", preparation, StringComparison.Ordinal);
        Assert.DoesNotContain("AppendHashExecutionResult(*executionContext)", preparation, StringComparison.Ordinal);
        Assert.DoesNotContain("observer->onProgressEvent(CreateFileStartedProgressEvent(result));", preparation, StringComparison.Ordinal);

        Assert.Contains("PrepareFileMetaResult(HashExecutionContext *executionContext, HashResult& result", result, StringComparison.Ordinal);
        Assert.Contains("uint64_t ResolveHashFileSizeAndTrack(HashExecutionContext *executionContext, sunjwbase::OsFile& osFile, bool isSizeCaled, ULLongVector& fSizes, uint32_t fileIndex, HashResult& result);", fileSizeAccountingHeader, StringComparison.Ordinal);
        Assert.Contains("uint64_t ResolveHashFileSizeAndTrack(HashExecutionContext *executionContext, sunjwbase::OsFile& osFile, bool isSizeCaled, ULLongVector& fSizes, uint32_t fileIndex, HashResult& result)", fileSizeAccounting, StringComparison.Ordinal);
        Assert.Contains("result.meta.size = fsize;", fileSizeAccounting, StringComparison.Ordinal);
        Assert.Contains("AddHashExecutionTotalSize(*executionContext, fsize);", fileSizeAccounting, StringComparison.Ordinal);
        Assert.Contains("ReplaceHashExecutionCountedFileSize(*executionContext, fSizes[fileIndex], fsize);", fileSizeAccounting, StringComparison.Ordinal);
        Assert.Contains("fSizes[fileIndex] = fsize;", fileSizeAccounting, StringComparison.Ordinal);
        Assert.Contains("uint64_t fsize = ResolveHashFileSizeAndTrack(executionContext, osFile, isSizeCaled, fSizes, fileIndex, result);", result, StringComparison.Ordinal);
        Assert.DoesNotContain("uint64_t fsize = osFile.getLength();", result, StringComparison.Ordinal);
        Assert.DoesNotContain("InitializeFileHashing(const HashRequest& request, HashExecutionContext *executionContext", result, StringComparison.Ordinal);
        Assert.DoesNotContain("FinalizeDigestStrings(const HashRequest& request", result, StringComparison.Ordinal);
        Assert.DoesNotContain("ReplaceHashExecutionCountedFileSize(*executionContext, fSizes[fileIndex], fsize);", result, StringComparison.Ordinal);
        Assert.Contains("tstrFileVersion = ResolveHashFileVersion(osFile, path);", result, StringComparison.Ordinal);
        Assert.DoesNotContain("void CompleteSuccessfulFileHashing(", result, StringComparison.Ordinal);
        Assert.DoesNotContain("void CompleteOpenedFileAttempt(", result, StringComparison.Ordinal);
        Assert.DoesNotContain("void EmitHashResult(", result, StringComparison.Ordinal);
        Assert.DoesNotContain("void EmitErrorResult(", result, StringComparison.Ordinal);
        Assert.Contains("sunjwbase::tstring ResolveHashFileVersion(sunjwbase::OsFile& osFile, const TCHAR *path);", fileVersionResolverHeader, StringComparison.Ordinal);
        Assert.Contains("sunjwbase::tstring ResolveHashFileVersion(sunjwbase::OsFile& osFile, const TCHAR *path)", fileVersionResolver, StringComparison.Ordinal);
        Assert.Contains("WindowsComm::FileVersionHelper fvHelper(osFile);", fileVersionResolver, StringComparison.Ordinal);
        Assert.Contains("return WindowsComm::GetExeFileVersion((TCHAR *)path);", fileVersionResolver, StringComparison.Ordinal);
        Assert.Contains("struct HashDigestRuntimePlan", digestRuntimePlanHeader, StringComparison.Ordinal);
        Assert.Contains("HashDigestRuntimePlan CreateHashDigestRuntimePlan(const HashJobExecutionPlan& executionPlan);", digestRuntimePlanHeader, StringComparison.Ordinal);
        Assert.Contains("const HashDigestQueuePlan& digestQueuePlan;", digestRuntimePlanHeader, StringComparison.Ordinal);
        Assert.Contains("HashDigestRuntimePlan(const DigestUpdateRequest& updateRequest, HashDigestExecutionMode executionMode, unsigned int bufferLength, const HashDigestQueuePlan& queuePlan)", digestRuntimePlanHeader, StringComparison.Ordinal);
        Assert.Contains("return HashDigestRuntimePlan(", digestRuntimePlan, StringComparison.Ordinal);
        Assert.Contains("GetHashJobDigestQueuePlan(executionPlan));", digestRuntimePlan, StringComparison.Ordinal);
        Assert.Contains("return digestRuntimePlan.digestQueuePlan;", digestRuntimePlan, StringComparison.Ordinal);
        Assert.Contains("bool CompleteOpenedFileDigestExecution(HashExecutionContext *executionContext, FileExecutionState *executionState, bool wasStopped);", digestCompletionHeader, StringComparison.Ordinal);
        Assert.Contains("bool CompleteOpenedFileDigestExecution(HashExecutionContext *executionContext, FileExecutionState *executionState, bool wasStopped)", digestCompletion, StringComparison.Ordinal);
        Assert.Contains("if (CompleteOpenedFileDigestExecution(executionContext, executionState, wasStopped))", digestPipeline, StringComparison.Ordinal);
        Assert.Contains("if (ShouldStopHashExecution(*executionContext))", digestCompletion, StringComparison.Ordinal);

        Assert.Contains("void ExecuteOpenedFileAttemptCompletionWorkflow(HashExecutionContext *executionContext, const HashRequest& request, HashResult& result, uint32_t fileIndex, bool isSizeCaled,", fileAttemptCompletionWorkflowHeader, StringComparison.Ordinal);
        Assert.Contains("void ExecuteFileAttemptCompletionWorkflow(HashExecutionContext *executionContext, const HashRequest& request, HashResult& result, uint32_t fileIndex, bool isSizeCaled,", fileAttemptCompletionWorkflowHeader, StringComparison.Ordinal);
        Assert.Contains("void ExecuteOpenedFileAttemptCompletionWorkflow(HashExecutionContext *executionContext, const HashRequest& request, HashResult& result, uint32_t fileIndex, bool isSizeCaled,", fileAttemptCompletionWorkflow, StringComparison.Ordinal);
        Assert.Contains("void ExecuteFileAttemptCompletionWorkflow(HashExecutionContext *executionContext, const HashRequest& request, HashResult& result, uint32_t fileIndex, bool isSizeCaled,", fileAttemptCompletionWorkflow, StringComparison.Ordinal);
        Assert.Contains("if (executionState.fileAttemptState.readFailed)", fileAttemptCompletionWorkflow, StringComparison.Ordinal);
        Assert.Contains("CompleteSuccessfulFileHashing(executionContext, request, result, fileIndex, isSizeCaled, executionState);", fileAttemptCompletionWorkflow, StringComparison.Ordinal);
        Assert.Contains("CompleteOpenedFileAttempt(executionContext, request, result, fileIndex, isSizeCaled, executionState);", fileAttemptCompletionWorkflow, StringComparison.Ordinal);
        Assert.Contains("EmitOpenFileError(executionContext, result, executionState.fileAttemptState.openErrorText);", fileAttemptCompletionWorkflow, StringComparison.Ordinal);
        Assert.Contains("FinishFileProcessing(executionContext);", fileAttemptCompletionWorkflow, StringComparison.Ordinal);

        Assert.Contains("void PublishWholeProgressAfterFile(HashExecutionContext *executionContext, const HashRequest& request, bool isSizeCaled, uint32_t fileIndex);", successfulFileCompletionWorkflowHeader, StringComparison.Ordinal);
        Assert.Contains("void ExecuteSuccessfulFileHashingWorkflow(HashExecutionContext *executionContext, const HashRequest& request, HashResult& result, uint32_t fileIndex, bool isSizeCaled,", successfulFileCompletionWorkflowHeader, StringComparison.Ordinal);
        Assert.Contains("void PublishWholeProgressAfterFile(HashExecutionContext *executionContext, const HashRequest& request, bool isSizeCaled, uint32_t fileIndex)", successfulFileCompletionWorkflow, StringComparison.Ordinal);
        Assert.Contains("void ExecuteSuccessfulFileHashingWorkflow(HashExecutionContext *executionContext, const HashRequest& request, HashResult& result, uint32_t fileIndex, bool isSizeCaled,", successfulFileCompletionWorkflow, StringComparison.Ordinal);
        Assert.Contains("observer->onProgressEvent(CreateFileCalculatedProgressEvent());", successfulFileCompletionWorkflow, StringComparison.Ordinal);
        Assert.Contains("FinalizeDigestStrings(request, executionState.hashContexts, executionState.digestBundle);", successfulFileCompletionWorkflow, StringComparison.Ordinal);
        Assert.Contains("UpdateWholeProgressAfterFile(executionContext, request, isSizeCaled, fileIndex);", successfulFileCompletionWorkflow, StringComparison.Ordinal);
        Assert.Contains("PopulateDigestResult(request, result, executionState.digestBundle);", successfulFileCompletionWorkflow, StringComparison.Ordinal);
        Assert.Contains("void PublishErrorMessageResult(HashExecutionContext *executionContext, HashResult& result, const sunjwbase::tstring& errorText);", errorResultWorkflowHeader, StringComparison.Ordinal);
        Assert.Contains("void PublishErrorMessageResult(HashExecutionContext *executionContext, HashResult& result, const sunjwbase::tstring& errorText)", errorResultWorkflow, StringComparison.Ordinal);
        Assert.Contains("result.error = errorText;", errorResultWorkflow, StringComparison.Ordinal);
        Assert.Contains("EmitErrorResult(executionContext, result);", errorResultWorkflow, StringComparison.Ordinal);
        Assert.Contains("void PublishMetaResultEvent(HashExecutionContext *executionContext, HashResult& result);", resultEventWorkflowHeader, StringComparison.Ordinal);
        Assert.Contains("void PublishHashResultEvent(HashExecutionContext *executionContext, HashResult& result, bool uppercase);", resultEventWorkflowHeader, StringComparison.Ordinal);
        Assert.Contains("void PublishErrorResultEvent(HashExecutionContext *executionContext, HashResult& result);", resultEventWorkflowHeader, StringComparison.Ordinal);
        Assert.Contains("void PublishFileFinishedEvent(HashExecutionContext *executionContext);", resultEventWorkflowHeader, StringComparison.Ordinal);
        Assert.Contains("void PublishMetaResultEvent(HashExecutionContext *executionContext, HashResult& result)", resultEventWorkflow, StringComparison.Ordinal);
        Assert.Contains("void PublishHashResultEvent(HashExecutionContext *executionContext, HashResult& result, bool uppercase)", resultEventWorkflow, StringComparison.Ordinal);
        Assert.Contains("void PublishErrorResultEvent(HashExecutionContext *executionContext, HashResult& result)", resultEventWorkflow, StringComparison.Ordinal);
        Assert.Contains("void PublishFileFinishedEvent(HashExecutionContext *executionContext)", resultEventWorkflow, StringComparison.Ordinal);
        Assert.Contains("observer->onProgressEvent(CreateFileMetaReadyProgressEvent(result));", resultEventWorkflow, StringComparison.Ordinal);
        Assert.Contains("observer->onProgressEvent(CreateFileHashReadyProgressEvent(result, uppercase));", resultEventWorkflow, StringComparison.Ordinal);
        Assert.Contains("observer->onProgressEvent(CreateFileFailedProgressEvent(result));", resultEventWorkflow, StringComparison.Ordinal);
        Assert.Contains("observer->onProgressEvent(CreateFileFinishedProgressEvent());", resultEventWorkflow, StringComparison.Ordinal);

        Assert.Contains("void UpdateWholeProgressAfterFile(HashExecutionContext *executionContext, const HashRequest& request, bool isSizeCaled, uint32_t fileIndex)", publisher, StringComparison.Ordinal);
        Assert.Contains("void CompleteSuccessfulFileHashing(HashExecutionContext *executionContext, const HashRequest& request, HashResult& result, uint32_t fileIndex, bool isSizeCaled,", publisher, StringComparison.Ordinal);
        Assert.Contains("void CompleteOpenedFileAttempt(HashExecutionContext *executionContext, const HashRequest& request, HashResult& result, uint32_t fileIndex, bool isSizeCaled,", publisher, StringComparison.Ordinal);
        Assert.Contains("PublishWholeProgressAfterFile(executionContext, request, isSizeCaled, fileIndex);", publisher, StringComparison.Ordinal);
        Assert.Contains("ExecuteSuccessfulFileHashingWorkflow(executionContext, request, result, fileIndex, isSizeCaled, executionState);", publisher, StringComparison.Ordinal);
        Assert.Contains("ExecuteOpenedFileAttemptCompletionWorkflow(executionContext, request, result, fileIndex, isSizeCaled, executionState);", publisher, StringComparison.Ordinal);
        Assert.Contains("ExecuteFileAttemptCompletionWorkflow(executionContext, request, result, fileIndex, isSizeCaled, executionState);", publisher, StringComparison.Ordinal);
        Assert.Contains("void EmitHashResult(HashExecutionContext *executionContext, HashResult& result, bool uppercase)", publisher, StringComparison.Ordinal);
        Assert.Contains("void EmitErrorResult(HashExecutionContext *executionContext, HashResult& result)", publisher, StringComparison.Ordinal);
        Assert.Contains("PublishErrorMessageResult(executionContext, result, errorText);", publisher, StringComparison.Ordinal);
        Assert.Contains("EmitErrorMessageResult(executionContext, result, sunjwbase::tstring(errorText));", publisher, StringComparison.Ordinal);
        Assert.Contains("EmitErrorMessageResult(executionContext, result, sunjwbase::strtotstr(std::string(\"Failed to read file while hashing.\")));", publisher, StringComparison.Ordinal);
        Assert.Contains("PublishMetaResultEvent(executionContext, result);", publisher, StringComparison.Ordinal);
        Assert.Contains("PublishHashResultEvent(executionContext, result, uppercase);", publisher, StringComparison.Ordinal);
        Assert.Contains("PublishErrorResultEvent(executionContext, result);", publisher, StringComparison.Ordinal);
        Assert.Contains("PublishFileFinishedEvent(executionContext);", publisher, StringComparison.Ordinal);

        Assert.Contains("#include \"Common/HashDigestExecution.h\"", internalHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashDigestExecutionMode.h\"", internalHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashDigestContextOps.h\"", internalHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashDigestOperationRegistry.h\"", internalHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashDigestLifecycle.h\"", internalHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashDigestBufferPlan.h\"", internalHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashDigestCompletion.h\"", internalHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashDigestQueue.h\"", internalHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashDigestQueuePlan.h\"", internalHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashDigestRuntimePlan.h\"", internalHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashDigestPipeline.h\"", internalHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashDigestSinglePass.h\"", internalHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashDigestUpdater.h\"", internalHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashFileAttemptCompletionWorkflow.h\"", internalHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashFileAttemptWorkflow.h\"", internalHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashFileResultWorkflow.h\"", internalHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashFileAttemptStateOps.h\"", internalHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashFileSizeAccounting.h\"", internalHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashFileVersionResolver.h\"", internalHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashJobExecutionPlan.h\"", internalHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashJobLifecycleWorkflow.h\"", internalHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashPreparationPlan.h\"", internalHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashPreScanSizeProbe.h\"", internalHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashPreScanSizeAccounting.h\"", internalHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashPreScanWorkflow.h\"", internalHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashPreparationWorkflow.h\"", internalHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashProgressTracker.h\"", internalHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashErrorResultWorkflow.h\"", internalHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashResultEventWorkflow.h\"", internalHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashResultPublisher.h\"", internalHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashSuccessfulFileCompletionWorkflow.h\"", internalHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashExecutionContext.h\"", internalHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashProgressSink.h\"", internalHeader, StringComparison.Ordinal);
        Assert.DoesNotContain("#include \"Common/HashEngineObserver.h\"", internalHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashRequest.h\"", internalHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashSchedulerDispatch.h\"", internalHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashSchedulerPlan.h\"", internalHeader, StringComparison.Ordinal);
        Assert.Contains("const HashRequest& request", internalHeader, StringComparison.Ordinal);
        Assert.Contains("bool RunHashScheduler(HashExecutionContext *executionContext, const HashRequest& request, const HashJobExecutionPlan& executionPlan, bool isSizeCaled, ULLongVector& fSizes);", internalHeader, StringComparison.Ordinal);
        Assert.Contains("bool RunFileHashAttempt(HashExecutionContext *executionContext, const HashRequest& request, uint32_t fileIndex, const sunjwbase::tstring& fullPath, bool isSizeCaled, ULLongVector& fSizes,", internalHeader, StringComparison.Ordinal);
        Assert.Contains("FileExecutionState *executionState", internalHeader, StringComparison.Ordinal);
        Assert.DoesNotContain("void EmitHashResult(HashExecutionContext *executionContext, HashResult& result, bool uppercase);", internalHeader, StringComparison.Ordinal);
    }

    [Fact]
    public void BridgeConsumers_NowConsumeHashResultAcrossManagedAndRealtimeAdapters()
    {
        string managedDispatch = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\ManagedBridgeDispatch.h");
        string managedHashMgmtAccess = RepositoryTestContext.ReadTextFile(@"trunk\source\Common\ManagedHashMgmtAccess.h");
        string clrHashResultNet = RepositoryTestContext.ReadTextFile(@"sub-proj\fHashClrBridge\HashResultNet.h");
        string clrMgmt = RepositoryTestContext.ReadTextFile(@"sub-proj\fHashClrBridge\HashMgmtClr.cpp");
        string clrMgmtHeader = RepositoryTestContext.ReadTextFile(@"sub-proj\fHashClrBridge\HashMgmtClr.h");
        string clrDelegatesHeader = RepositoryTestContext.ReadTextFile(@"sub-proj\fHashClrBridge\UIBridgeDelegates.h");
        string clrDelegatesSource = RepositoryTestContext.ReadTextFile(@"sub-proj\fHashClrBridge\UIBridgeDelegates.cpp");
        string uwpHashResultNet = RepositoryTestContext.ReadTextFile(@"sub-proj\fHashWinRtBridge\HashResultNet.h");
        string uwpMgmt = RepositoryTestContext.ReadTextFile(@"sub-proj\fHashWinRtBridge\HashMgmt.cpp");
        string uwpMgmtHeader = RepositoryTestContext.ReadTextFile(@"sub-proj\fHashWinRtBridge\HashMgmt.h");
        string uwpDelegateHeader = RepositoryTestContext.ReadTextFile(@"sub-proj\fHashWinRtBridge\UIBridgeDelegate.h");
        string uwpDelegateSource = RepositoryTestContext.ReadTextFile(@"sub-proj\fHashWinRtBridge\UIBridgeDelegate.cpp");
        string mfcHeader = RepositoryTestContext.ReadTextFile(@"trunk\source\WinMFC\UIBridgeMFC.h");
        string mfcSource = RepositoryTestContext.ReadTextFile(@"trunk\source\WinMFC\UIBridgeMFC.cpp");
        string wuiHeader = RepositoryTestContext.ReadTextFile(@"sub-proj\fHashClrBridge\UIBridgeWUI.h");
        string wuiSource = RepositoryTestContext.ReadTextFile(@"sub-proj\fHashClrBridge\UIBridgeWUI.cpp");
        string uwpHeader = RepositoryTestContext.ReadTextFile(@"sub-proj\fHashWinRtBridge\UIBridgeUwp.h");
        string uwpSource = RepositoryTestContext.ReadTextFile(@"sub-proj\fHashWinRtBridge\UIBridgeUwp.cpp");
        string macHeader = RepositoryTestContext.ReadTextFile(@"trunk\source\OSXUI\UIBridgeMacSwift.h");
        string macSource = RepositoryTestContext.ReadTextFile(@"trunk\source\OSXUI\UIBridgeMacSwift.mm");
        string hashBridgeMac = RepositoryTestContext.ReadTextFile(@"trunk\source\OSXUI\HashBridge.mm");
        string searchHeader = RepositoryTestContext.ReadTextFile(@"trunk\source\WinMFC\FilesHashSearchController.h");
        string searchSource = RepositoryTestContext.ReadTextFile(@"trunk\source\WinMFC\FilesHashSearchController.cpp");
        string winUiPage = RepositoryTestContext.ReadTextFile(@"trunk\source\WinUI\MainPage.xaml.cs");
        string winUwpPage = RepositoryTestContext.ReadTextFile(@"trunk\source\WinUWP\MainPage.xaml.cs");

        Assert.Contains("#include \"Common/HashResultProjection.h\"", managedDispatch, StringComparison.Ordinal);
        Assert.Contains("DispatchManagedBridgeResultByType(const HashResult& result", managedDispatch, StringComparison.Ordinal);
        Assert.Contains("ProjectHashResultToNet<TResultDataNet, TResultStateNet>(result, convertString)", managedDispatch, StringComparison.Ordinal);
        Assert.DoesNotContain("DispatchManagedBridgeResultByType(const ResultData& result", managedDispatch, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashResultProjection.h\"", managedHashMgmtAccess, StringComparison.Ordinal);
        Assert.Contains("CreateProjectedDigestMatchingHashResults<THashResultNet, THashResultStateNet, TResultArray>(", managedHashMgmtAccess, StringComparison.Ordinal);
        Assert.Contains("static inline TResultArray CreateProjectedManagedDigestMatchingHashResults(", managedHashMgmtAccess, StringComparison.Ordinal);

        Assert.Contains("public enum class HashResultStateNet", clrHashResultNet, StringComparison.Ordinal);
        Assert.Contains("public value struct HashResultNet", clrHashResultNet, StringComparison.Ordinal);
        Assert.Contains("cli::array<HashResultNet>^ FindHashResults(System::String^ sstrHashToFind);", clrMgmtHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashThreadLaunch.h\"", clrMgmt, StringComparison.Ordinal);
        Assert.Contains("HANDLE workThread = m_hWorkThread;", clrMgmt, StringComparison.Ordinal);
        Assert.Contains("RestartHashWorkerThread(&workThread, m_pThreadData, &thredID);", clrMgmt, StringComparison.Ordinal);
        Assert.Contains("CloseHashWorkerThreadHandle(&workThread);", clrMgmt, StringComparison.Ordinal);
        Assert.DoesNotContain("_beginthreadex", clrMgmt, StringComparison.Ordinal);
        Assert.Contains("CreateProjectedManagedDigestMatchingHashResults<HashResultNet, HashResultStateNet, cli::array<HashResultNet>^>(", clrMgmt, StringComparison.Ordinal);
        Assert.DoesNotContain("FindResult(System::String^ sstrHashToFind)", clrMgmtHeader, StringComparison.Ordinal);
        Assert.DoesNotContain("CreateCompatibilityResultDataNetArray(", clrMgmt, StringComparison.Ordinal);
        Assert.Contains("#include \"HashResultNet.h\"", clrDelegatesHeader, StringComparison.Ordinal);
        Assert.Contains("public delegate void HashResultEventHandler(HashResultNet);", clrDelegatesHeader, StringComparison.Ordinal);
        Assert.Contains("void ShowFileHash(HashResultNet hashResultNet, bool uppercase);", clrDelegatesHeader, StringComparison.Ordinal);
        Assert.Contains("event HashResultHashEventHandler^ ShowFileHashHandler;", clrDelegatesHeader, StringComparison.Ordinal);
        Assert.Contains("void UIBridgeDelegates::ShowFileHash(HashResultNet hashResultNet, bool uppercase)", clrDelegatesSource, StringComparison.Ordinal);
        Assert.Contains("ShowFileHashHandler(hashResultNet, uppercase);", clrDelegatesSource, StringComparison.Ordinal);

        Assert.Contains("public enum class HashResultStateNet", uwpHashResultNet, StringComparison.Ordinal);
        Assert.Contains("public value struct HashResultNet", uwpHashResultNet, StringComparison.Ordinal);
        Assert.Contains("Platform::Array<HashResultNet>^ FindHashResults(Platform::String^ pstrHashToFind);", uwpMgmtHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashThreadLaunch.h\"", uwpMgmt, StringComparison.Ordinal);
        Assert.Contains("RestartHashWorkerThread(&m_hWorkThread, &m_threadData, &thredID);", uwpMgmt, StringComparison.Ordinal);
        Assert.DoesNotContain("_beginthreadex", uwpMgmt, StringComparison.Ordinal);
        Assert.Contains("CreateProjectedManagedDigestMatchingHashResults<HashResultNet, HashResultStateNet, Array<HashResultNet>^>(", uwpMgmt, StringComparison.Ordinal);
        Assert.DoesNotContain("FindResult(Platform::String^ pstrHashToFind)", uwpMgmtHeader, StringComparison.Ordinal);
        Assert.DoesNotContain("CreateCompatibilityResultDataNetArray(", uwpMgmt, StringComparison.Ordinal);
        Assert.Contains("#include \"HashResultNet.h\"", uwpDelegateHeader, StringComparison.Ordinal);
        Assert.Contains("public delegate void HashResultEventHandler(HashResultNet);", uwpDelegateHeader, StringComparison.Ordinal);
        Assert.Contains("void ShowFileHash(HashResultNet hashResultNet, Platform::Boolean uppercase);", uwpDelegateHeader, StringComparison.Ordinal);
        Assert.Contains("event HashResultHashEventHandler^ ShowFileHashHandler;", uwpDelegateHeader, StringComparison.Ordinal);
        Assert.Contains("void UIBridgeDelegate::ShowFileHash(HashResultNet hashResultNet, Boolean uppercase)", uwpDelegateSource, StringComparison.Ordinal);
        Assert.Contains("ShowFileHashHandler(hashResultNet, uppercase);", uwpDelegateSource, StringComparison.Ordinal);

        Assert.Contains("virtual void onFileResultEvent(const HashResult& result,", mfcHeader, StringComparison.Ordinal);
        Assert.Contains("#include \"Common/HashResultRender.h\"", mfcHeader, StringComparison.Ordinal);
        Assert.DoesNotContain("#include \"Common/HashResultCompatibility.h\"", mfcHeader, StringComparison.Ordinal);
        Assert.Contains("void UIBridgeMFC::onFileResultEvent(const HashResult& result,", mfcSource, StringComparison.Ordinal);
        Assert.Contains("case PROGRESS_EVENT_FILE_HASH_READY:", mfcSource, StringComparison.Ordinal);
        Assert.Contains("AppendResultSectionAndRefresh(result, RESULT_RENDER_SECTION_HASH, uppercaseDigest);", mfcSource, StringComparison.Ordinal);
        Assert.Contains("VisitHashResultDigestDisplayValues(result, uppercase", mfcSource, StringComparison.Ordinal);
        Assert.Contains("void UIBridgeMFC::AppendResultToHyperEdit(const HashResult& result,", mfcSource, StringComparison.Ordinal);
        Assert.DoesNotContain("CreateCompatibilityResultData(result);", mfcSource, StringComparison.Ordinal);
        Assert.Contains("void AppendResult(const HashResult& result);", searchHeader, StringComparison.Ordinal);
        Assert.Contains("VisitThreadDataHashResults(*m_threadData, [&](const HashResult& result)", searchSource, StringComparison.Ordinal);
        Assert.Contains("VisitThreadDataPathAndDigestMatchingHashResults(*m_threadData, tstrFileToFind, tstrHashToFind, [&](const HashResult& result)", searchSource, StringComparison.Ordinal);
        Assert.Contains("UIBridgeMFC::AppendResultToHyperEdit(result, GetThreadDataUppercase(*m_threadData), m_mainEdit);", searchSource, StringComparison.Ordinal);

        Assert.Contains("virtual void onFileResultEvent(const HashResult& result,", wuiHeader, StringComparison.Ordinal);
        Assert.Contains("DispatchProjectedResultToDelegate(const HashResult& result", wuiHeader, StringComparison.Ordinal);
        Assert.Contains("void UIBridgeWUI::onFileResultEvent(const HashResult& result,", wuiSource, StringComparison.Ordinal);
        Assert.Contains("DispatchManagedBridgeResultByType<HashResultNet, HashResultStateNet>(result, dispatchType, uppercase", wuiSource, StringComparison.Ordinal);
        Assert.Contains("GetManagedResultDispatchType(eventType)", wuiSource, StringComparison.Ordinal);
        Assert.Contains("m_uiBridgeDelegates->ShowFileHash(hashResultNet, hashUppercase);", wuiSource, StringComparison.Ordinal);

        Assert.Contains("virtual void onFileResultEvent(const HashResult& result,", uwpHeader, StringComparison.Ordinal);
        Assert.Contains("DispatchProjectedResultToDelegate(const HashResult& result", uwpHeader, StringComparison.Ordinal);
        Assert.Contains("void UIBridgeUwp::onFileResultEvent(const HashResult& result,", uwpSource, StringComparison.Ordinal);
        Assert.Contains("DispatchManagedBridgeResultByType<HashResultNet, HashResultStateNet>(result, dispatchType, uppercase", uwpSource, StringComparison.Ordinal);
        Assert.Contains("GetManagedResultDispatchType(eventType)", uwpSource, StringComparison.Ordinal);
        Assert.Contains("m_uiBridgeDelegate->ShowFileHash(hashResultNet, hashUppercase);", uwpSource, StringComparison.Ordinal);

        Assert.DoesNotContain("#include \"Common/HashResultCompatibility.h\"", macHeader, StringComparison.Ordinal);
        Assert.Contains("static ResultDataSwift *ConvertHashResultToSwift(const HashResult& result);", macHeader, StringComparison.Ordinal);
        Assert.Contains("virtual void onFileResultEvent(const HashResult& result,", macHeader, StringComparison.Ordinal);
        Assert.Contains("ResultDataSwift *resultSwift = UIBridgeMacSwift::ConvertHashResultToSwift(result);", macSource, StringComparison.Ordinal);
        Assert.Contains("void UIBridgeMacSwift::onFileResultEvent(const HashResult& result,", macSource, StringComparison.Ordinal);
        Assert.Contains("case PROGRESS_EVENT_FILE_HASH_READY:", macSource, StringComparison.Ordinal);
        Assert.DoesNotContain("CreateCompatibilityResultData(result);", macSource, StringComparison.Ordinal);
        Assert.Contains("ResultDataSwift *UIBridgeMacSwift::ConvertHashResultToSwift(const HashResult& result)", macSource, StringComparison.Ordinal);
        Assert.Contains("VisitThreadDataHashResults(*_thrdData, [&](const HashResult& result)", hashBridgeMac, StringComparison.Ordinal);
        Assert.Contains("ConvertHashResultToSwift(result);", hashBridgeMac, StringComparison.Ordinal);

        Assert.Contains("HashResultNet[] hashResultNetArray = m_mainWindow.HashMgmt.FindHashResults(strHashToFind);", winUiPage, StringComparison.Ordinal);
        Assert.Contains("private void AppendFileResultToTextMain(HashResultNet hashResult, bool uppercase)", winUiPage, StringComparison.Ordinal);
        Assert.Contains("private void ShowFindResult(string strHashToFind, HashResultNet[] hashResultNetArray)", winUiPage, StringComparison.Ordinal);
        Assert.Contains("AppendFileResultToTextMain(hashResult, m_uppercaseChecked);", winUiPage, StringComparison.Ordinal);
        Assert.Contains("private void UIBridgeHandlers_ShowFileHashHandler(HashResultNet hashResult, bool uppercase)", winUiPage, StringComparison.Ordinal);
        Assert.DoesNotContain("CreateCompatibilityResultData(", winUiPage, StringComparison.Ordinal);

        Assert.Contains("HashResultNet[] hashResultNetArray = m_hashMgmt.FindHashResults(strHashToFind);", winUwpPage, StringComparison.Ordinal);
        Assert.Contains("private void AppendFileResultToTextMain(HashResultNet hashResult, bool uppercase)", winUwpPage, StringComparison.Ordinal);
        Assert.Contains("private void ShowFindResult(string strHashToFind, HashResultNet[] hashResultNetArray)", winUwpPage, StringComparison.Ordinal);
        Assert.Contains("AppendFileResultToTextMain(hashResult, m_uppercaseChecked);", winUwpPage, StringComparison.Ordinal);
        Assert.Contains("private void UIBridgeDelegate_ShowFileHashHandler(HashResultNet hashResult, bool uppercase)", winUwpPage, StringComparison.Ordinal);
        Assert.DoesNotContain("CreateCompatibilityResultData(", winUwpPage, StringComparison.Ordinal);
    }
}
